name = "Latajacy Holender"
author = "kyanbasu"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4630b3635e4f266656e0524b9048e0aaf50422b95514ccd6bb53e12bc6e192d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
