name = "Latajacy Holender"
author = "kyanbasu"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b752f82610dd73edbe4f3d59080c40ee7a4cfd48912bc44b679a272b11a6b8e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
