name = "Latajacy Holender"
author = "kyanbasu"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "700d7275e81c4bc313fb5ed268ed99b89c0c30d32cd7ee03cd13bba898d202ae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
